env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.17.0
  - nightly-2017-04-28
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
  - if [ "${TRAVIS_RUST_VERSION}" = 1.17.0 ]; then
      rustfmt_vers=0.8.3;
      if ! rustfmt --version | grep -q $rustfmt_vers; then
        cargo install rustfmt --vers=$rustfmt_vers --force;
      fi
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      clippy_vers=0.0.128;
      if ! cargo clippy --version | grep -q $clippy_vers; then
        cargo install clippy --vers=$clippy_vers --force;
      fi
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = 1.17.0 ]; then
      (
        set -x;
        cargo fmt -- --write-mode=diff &&
        cargo test --release --verbose
      );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      (
        set -x;
        cargo clippy && cargo clippy --profile=test
      );
    fi
before_cache:
  - cargo prune
