env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - stable
sudo: false
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt;
  - rustup component add clippy;
script:
  - set -x;
    cargo fmt -- --check &&
    cargo clippy &&
    cargo clippy --profile=test &&
    cargo test --no-default-features --release --verbose
  - cargo check --examples
before_cache:
  - cargo prune
