env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.26.1
  - nightly-2018-05-29
sudo: false
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
    if [ "${TRAVIS_RUST_VERSION}" = nightly-2018-05-29 ] && [ "${TRAVIS_OS_NAME}" = linux ]; then
      rustup component add rustfmt-preview --toolchain nightly-2018-05-29 &&
      bash cargo_install.sh clippy 0.0.206;
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = 1.26.1 ]; then
      (
        set -x;
        cargo test --no-default-features --release --verbose
      );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      (
        set -x;
        cargo fmt -- --check &&
        cargo clippy && cargo clippy --profile=test
      );
    fi
  - cargo check --examples
before_cache:
  - cargo prune
