[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "https://docs.rs/crust"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.26.0"

[dependencies]
byteorder = "~1.0.0"
c_linked_list = "~1.1.0"
config_file_handler = "~0.7.0"
crossbeam = "~0.2.10"
igd = "~0.5.1"
libc = "~0.2.20"
log = "~0.3.6"
maidsafe_utilities = "~0.13.0"
mio = "~0.6.6"
net2 = "~0.2.27"
quick-error = "~1.1.0"
rand = "~0.3.14"
rust_sodium = "~0.3.0"
serde = "~1.0.2"
serde_derive = "~1.0.2"
serde_json = "~1.0.1"
tiny-keccak = "~1.2.1"
unwrap = "~1.1.0"

[dev-dependencies]
clap = "~2.22.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "~0.2"

[[example]]
bench = false
name = "crust_peer"
path = "examples/crust_peer.rs"
