[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://docs.maidsafe.net/crust/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.15.0"

[dependencies]
byteorder = "~0.5.1"
config_file_handler = "~0.3.0"
crossbeam = "~0.2.9"
get_if_addrs = "~0.4.0"
igd = "~0.4.2"
log = "~0.3.6"
maidsafe_utilities = "~0.6.0"
net2 = "~0.2.23"
quick-error = "~1.0.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"
tmp_mio = "~0.5.2"

[dependencies.clippy]
optional = true
version = "~0.0.76"
