[package]
name = "crust"
version = "0.5.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://maidsafe.net/crust/latest"
repository = "https://github.com/maidsafe/crust"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
libc = "~0.1.12"
cbor = "~0.3.16"
docopt = "~0.6.75"
rand = "~0.3.12"
rustc-serialize = "~0.3.16"
term = "~0.2.13"
time = "~0.1.34"
itertools = "~0.4.3"
igd = { version = "~0.2.1", features = [ "unstable" ] }
net2 = "~0.2.17"
temp_utp = "~0.6.19"
log = "~0.3.3"
crossbeam = "~0.1.6"

[dev-dependencies]
env_logger = "~0.3.2"

[[example]]
name = "simple_sender"
path = "examples/simple_sender.rs"
test = true
bench = false

[[example]]
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = true
bench = false

[[example]]
name = "crust_peer"
path = "examples/crust_peer.rs"
test = true
bench = false

[[example]]
name = "reporter"
path = "examples/reporter.rs"
test = true
bench = false

[[example]]
name = "simple_benchmark"
path = "examples/simple_benchmark.rs"
test = true
bench = false
