[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://maidsafe.net/crust/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.9.0"

[dependencies]
clippy = { version = "~0.0.46", optional = true }
config_file_handler = "~0.2.0"
crossbeam = "~0.2.8"
get_if_addrs = "~0.4.0"
itertools = "~0.4.10"
libc = "~0.2.7"
log = "~0.3.5"
maidsafe_utilities = "~0.4.0"
nat_traversal = "~0.3.1"
net2 = "~0.2.22"
rand = "~0.3.14"
rustc-serialize = "~0.3.18"
service_discovery = "~0.3.0"
socket_addr = "~0.1.0"
sodiumoxide = "~0.0.9"
temp_utp = "~0.8.0"
term = "~0.4.4"
time = "~0.1.34"

[dev-dependencies]
docopt = "~0.6.78"
void = "~1.0.1"
loggerv = "~0.2.0"

[[example]]
bench = false
name = "simple_sender"
path = "examples/simple_sender.rs"
test = false

[[example]]
bench = false
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = false

[[example]]
bench = false
name = "crust_peer"
path = "examples/crust_peer.rs"

[[example]]
bench = false
name = "reporter"
path = "examples/reporter.rs"
test = true

[[example]]
bench = false
name = "simple_benchmark"
path = "examples/simple_benchmark.rs"
test = false
