[package]
name = "crust"
version = "0.0.1"
authors = ["MaidSafe Dev team <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/crust/crust"
repository = "https://github.com/dirvine/crust"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"



[dependencies]
rustc-serialize = "*"
cbor = "*"

[[example]]
name = "simple_client"
path = "examples/simple_client.rs"
test = false
bench = false

[[example]]
name = "simple_server"
path = "examples/simple_server.rs"
test = false
bench = false
