[package]
name = "crust"
version = "0.2.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://maidsafe.net/crust/latest"
repository = "https://github.com/maidsafe/crust"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
libc = "*"
cbor = "*"
docopt = "*"
rand = "*"
rustc-serialize = "*"
term = "*"
time = "*"
asynchronous = "*"
utp = "*"
itertools = "*"
tempdir = "*"
igd = "0.1.3"

[[example]]
name = "simple_sender"
path = "examples/simple_sender.rs"
test = true
bench = false

[[example]]
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = true
bench = false

[[example]]
name = "crust_peer"
path = "examples/crust_peer.rs"
test = true
bench = false
