[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "https://docs.rs/crust"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.28.1"

[dependencies]
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
maidsafe_utilities = "0.14.0"
config_file_handler = "0.8.0"
quick-error = "1.2.0"
unwrap = "1.1"
tokio-core = "*"
tokio-io = "*"
futures = "*"
net2 = "*"
get_if_addrs = "*"
log = "*"
void = "*"
bytes = "0.4"
rand = "*"
rand_derive = "*"
env_logger = "*"
tiny-keccak = "1.3"
notify = "*"
maplit = "*"
net-literals = "0.1"
future-utils = "0.3.0"
igd = "*"

[[example]]
name = "connect"
path = "examples/connect.rs"

[[example]]
name = "exchange_data"
path = "examples/exchange_data.rs"
