[package]
name = "crust"
version = "0.0.62"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "p2p networking library. Automatically reconnect and manage connections."
documentation = "http://maidsafe.github.io/crust/crust"
repository = "https://github.com/dirvine/crust"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
libc = "*"
cbor = "*"
docopt = "*"
rand = "*"
rustc-serialize = "*"
sodiumoxide = "0.0.4"
term = "*"
time = "*"
asynchronous = "*"
utp = "*"

[[example]]
name = "simple_sender"
path = "examples/simple_sender.rs"
test = true
bench = false

[[example]]
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = true
bench = false

[[example]]
name = "crust_peer"
path = "examples/crust_peer.rs"
test = true
bench = false
