[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://maidsafe.net/crust/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.12.0"

[dependencies]
byteorder = "~0.5.1"
config_file_handler = "~0.3.0"
log = "~0.3.6"
maidsafe_utilities = "~0.6.0"
mio = { git = "https://github.com/ustulation/mio.git" }
nat_traversal = "~0.3.3"
net2 = "~0.2.23"
quick-error = "~1.0.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"
socket_addr = "~0.1.0"
env_logger = "~0.3.3"
get_if_addrs = "~0.4.0"

[dependencies.clippy]
optional = true
version = "~0.0.64"

[dev-dependencies]
docopt = "~0.6.80"
void = "~1.0.2"
crossbeam = "~0.2.9"

[[example]]
bench = false
name = "simple_demo"
path = "examples/simple_demo.rs"
test = false

[[example]]
bench = false
name = "mapping_client"
path = "examples/mapping_client.rs"
test = true

[[test]]
name = "send_and_receive"
path = "tests/send_and_receive.rs"
test = false

[[example]]
bench = false
name = "simple_sender"
path = "examples/simple_sender.rs"
test = false

[[example]]
bench = false
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = false

[[example]]
bench = false
name = "crust_peer"
path = "examples/crust_peer.rs"
test = false

[[example]]
bench = false
name = "reporter"
path = "examples/reporter.rs"
test = false

[[example]]
bench = false
name = "simple_benchmark"
path = "examples/simple_benchmark.rs"
test = false
